plugins {
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.7'
    id 'com.enonic.xp.app'
}

dependencies {
    // XP core
    implementation xplibs.api.core
    implementation xplibs.api.portal
    implementation xplibs.api.web
    compileOnly libs.jackson.databind
    compileOnly libs.micrometer.core
    include xplibs.content
    include xplibs.portal
    include xplibs.io
    include xplibs.auth
    include xplibs.websocket
    include xplibs.task
    include xplibs.event
    include xplibs.admin

    include libs.lib.asset
    include libs.lib.license
    include libs.lib.mustache
    include libs.lib.http.client
    include libs.lib.cron

    testImplementation "com.enonic.xp:testing:${xpVersion}"
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.1.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.3'
}

repositories {
    mavenCentral()
    xp.enonicRepo('dev')
}

test {
    useJUnitPlatform()
}

xp {
    scriptEngines = ['Nashorn', 'GraalJS']
}
